STRINGS = {
    'uz': {
        'welcome': "<b>Assalomu alaykum! Professional Arxitektor Botiga xush kelibsiz.</b>\n\nMen sizning talablaringiz asosida xalqaro standartlarga javob beradigan professional uy loyihalarini (DXF va PNG) yaratib beraman.\n\nYangi loyiha boshlash uchun '🏗️ Loyiha yaratish' tugmasini bosing.",
        'help': "🏠 <b>Yordam bo'limi:</b>\n\n1. Yer maydoni o'lchamlarini kiriting.\n2. Qavatlar va xonalar sonini ayting.\n3. Maxsus uslub (Modern yoki Klassik) va boshqa talablaringizni yozing.\n\nMen sizga AutoCAD va boshqa CAD dasturlarida ochiladigan tayyor .dxf chizmasini taqdim etaman.",
        'parsing': "🔍 <b>AI sizning talablaringizni tahlil qilmoqda va professional layout yaratmoqda...</b>",
        'error_parse': "❌ <b>Xatolik yuz berdi:</b>\n\n{error}\n\nIltimos, talablaringizni aniqroq yozing.",
        'generating': "📐 <b>Sizning loyihangiz professional standartlar asosida chizilmoqda...</b>",
        'btn_help': "❓ Yordam",
        'btn_settings': "⚙️ Sozlamalar",
        'btn_create': "🏗️ Loyiha yaratish",
        'btn_cancel': "❌ Bekor qilish",
        'lang_changed': "✅ Til o'zbekchaga o'zgartirildi.",
        'select_lang': "🌍 <b>Tilni tanlang / Select Language:</b>",
        'ask_dimensions': "📏 <b>Yer maydoni o'lchamlarini kiriting:</b>\n(Masalan: 12x15m)",
        'ask_floors': "🏢 <b>Qavatlar sonini kiriting:</b>",
        'ask_rooms': "🛌 <b>Xonalar tarkibini kiriting:</b>\n(Masalan: 3 ta yotoqxona, zal va hol)",
        'ask_notes': "📝 <b>Maxsus talablar va uslub:</b>\n(Masalan: Zamonaviy uslub, panoramali derazalar, minimalizm)",
        'invalid_input': "⚠️ Noto'g'ri ma'lumot kiritildi. Iltimos, qaytadan urinib ko'ring.",
        'room_dims': "📊 <b>Loyiha hisoboti:</b>",
        'canceled': "❌ Jarayon bekor qilindi.",
        'cmd_start': "Botni ishga tushirish",
        'cmd_help': "Yordam ko'rsatish"
    },
    'en': {
        'welcome': "<b>Welcome to the Professional Architect Bot!</b>\n\nI generate professional architectural plans (DXF & PNG) based on your requirements and international standards.\n\nPress '🏗️ Create Project' to start.",
        'help': "🏠 <b>Help Section:</b>\n\n1. Enter your land dimensions.\n2. Specify number of floors and rooms.\n3. Define style (Modern or Classic) and other specific notes.\n\nI will provide a ready-made .dxf file compatible with AutoCAD and other CAD software.",
        'parsing': "🔍 <b>AI is analyzing your requirements and designing a professional layout...</b>",
        'error_parse': "❌ <b>An error occurred:</b>\n\n{error}\n\nPlease try to be more specific with your requirements.",
        'generating': "📐 <b>Your project is being drafted according to professional standards...</b>",
        'btn_help': "❓ Help",
        'btn_settings': "⚙️ Settings",
        'btn_create': "🏗️ Create Project",
        'btn_cancel': "❌ Cancel",
        'lang_changed': "✅ Language changed to English.",
        'select_lang': "🌍 <b>Select language / Tilni tanlang:</b>",
        'ask_dimensions': "📏 <b>Enter land dimensions:</b>\n(e.g., 12x15m)",
        'ask_floors': "🏢 <b>Enter number of floors:</b>",
        'ask_rooms': "🛌 <b>Enter room composition:</b>\n(e.g., 3 bedrooms, living room, and a hall)",
        'ask_notes': "📝 <b>Special requirements and style:</b>\n(e.g., Modern style, panoramic windows, minimalism)",
        'invalid_input': "⚠️ Invalid input. Please try again.",
        'room_dims': "📊 <b>Project Report:</b>",
        'canceled': "❌ Canceled.",
        'cmd_start': "Start the bot",
        'cmd_help': "Show help"
    }
}
